title: Hello pikachu987 World
description: pikachu987 daily blog

url: http://pikachu987.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Blog
   url: /index.html
 - title: Contact
   url: /contact

social:
   github: pikachu987
   facebook: gaunho.kim?ref=bookmarks
   email: pikachu77769@gmail.com

google_analytics: "UA-80258859-1"
