title: pikachu987 Blog
description: pikachu987 daily blog

url: http://pikachu987.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: pikachu987
   facebook: gaunho.kim?ref=bookmarks
   email: pikachu987@naver.com

google_analytics: "UA-58263416-1"
