# Site settings
title: Guan Ho(pikachu987) Blog
description: Hello Guanho Kim World
keywords: pikachu987
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
